[package]
name = "server"
version = "0.1.0"
authors = ["Arnaud Leherpeur <arnaud.leherpeur@taultek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"